name = "NotVanilla"
author = "R4TWT"
version = "0.0.8-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7f9540b1e5d8b0be47dff1b795d00bdcadad8d2f1eb80a77833d6334eca6445"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
