name = "NotVanilla"
author = "R4TWT"
version = "0.0.11-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9fb7d92aeaa6311cfb3e9a0d771a6eb63f64c35fdc0cfc113d1944ecfb57321f"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21", "1.21.1"]
