name = "NotVanilla"
author = "R4TWT"
version = "0.0.1-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e99ec0d2d94572d6b6fe07a72644646970cafa88e72f3b79aa89629352515ec7"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
